name: JIRA Linker

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  add-jira-link:
    runs-on: ubuntu-latest
    steps:
      - name: Add JIRA Link to PR Title
        run: |
          pr_title=$(jq -r '.pull_request.title' $GITHUB_EVENT_PATH)
          jira_url="https://idewave.atlassian.net/browse/"
          ticket=$(echo $pr_title | grep -o 'AB-[0-9]\+')
          
          if [[ ! -z "$ticket" ]]; then
            jira_link="[${ticket}](${jira_url}${ticket})"
            new_title=$(echo $pr_title | sed "s#${ticket}#${jira_link}#")
            echo "Updating PR title to: $new_title"
          
            # Update PR title using GitHub API with Python
            python3 - <<EOF
  import os
  import json
  import requests
  
  title = os.getenv('new_title')
  pr_number = os.getenv('GITHUB_EVENT_PATH').split('/')[-1].split('.')[0]
  token = os.getenv('GITHUB_TOKEN')
  repo = os.getenv('GITHUB_REPOSITORY')
  
  headers = {
"Authorization": f"token {token}",
"Accept": "application/vnd.github.v3+json"
}

  data = {
"title": title
}

  response = requests.patch(f"https://api.github.com/repos/{repo}/pulls/{pr_number}", headers=headers, json=data)

if response.status_code == 200:
  print("PR title updated successfully")
else:
  print("Failed to update PR title")
  EOF
  fi
env:
  new_title: ${{ steps.add-jira-link.outputs.new_title }}
